# services.yaml

# Este archivo configura los servicios personalizados y establece los parámetros necesarios.
# Los archivos en el subdirectorio packages/ configuran dependencias adicionales.

parameters:
    # Define aquí parámetros que no necesitan cambiarse en cada despliegue
    # https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

services:
    # Configuración predeterminada para los servicios en este archivo
    _defaults:
        autowire: true      # Inyecta automáticamente las dependencias en los servicios
        autoconfigure: true # Registra automáticamente servicios como comandos, suscriptores de eventos, etc.

    # Permite el uso de clases en el directorio src/ como servicios
    # Esto crea un servicio por cada clase cuyo id es el nombre completo de la clase
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Definiciones de servicios adicionales
    # Las configuraciones más específicas sobrescriben las configuraciones anteriores

    # Servicio ConfigChecker para verificar la existencia del archivo de configuración .env
    App\Services\ConfigChecker:
        arguments:
            $path: '%kernel.project_dir%/.env'

    # Servicio DatabaseConnection para manejar la conexión a la base de datos
    # (se pueden agregar configuraciones adicionales si es necesario)
    App\Services\DatabaseConnection: ~

    # Servicio DataFetcher para obtener datos de la base de datos
    App\Services\DataFetcher:
        arguments:
            $dbConnection: '@App\Services\DatabaseConnection'
